#pragma once
#include "DefaultAttack.h"

#include "FireBlast.h"
#include "Gust.h"
#include "Lightning.h"
#include "RockSlide.h"
#include "DynamicPunch.h"
#include "LeafBlade.h"
#include "ThunderFang.h"
#include "IceFang.h"
#include "FireFang.h"
#include "Pound.h"

#include "PoisonPowder.h"
#include "SleepPowder.h"
#include "StunSpore.h"
#include "MetalClaw.h"
#include "Bind.h"
#include "CrossChop.h"
#include "FeintAttack.h"
#include "RockSmash.h"
#include "ShadowClaw.h"
#include "TriAttack.h"

#include "WakeUpSlap.h"
#include "WingAttack.h"
#include "VineWhip.h"
#include "Waterfall.h"
#include "SheerCold.h"
#include "DracoMeteor.h"