#pragma once
#include "FireBlast.h"
#include "Gust.h"
#include "Lightning.h"
#include "RockSlide.h"
#include "DynamicPunch.h"
#include "LeafBlade.h"
#include "ThunderFang.h"
#include "IceFang.h"
#include "FireFang.h"
#include "Pound.h"

#include "PoisonPowder.h"
#include "SleepPowder.h"
#include "StunSpore.h"
#include "MetalClaw.h"